version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}-{branch}'
nuget:
  account_feed: true
build:
  parallel: true
  verbosity: normal
artifacts:
- path: '**\*.nupkg'
  name: nupkg
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  auth_token:
    secure: UKi94d2MuFkTQQi/a/fCIk77vNm1Iqi90f7PkeJKs8HVvCuGGhxlqNKKblKL6iL+
  artifact: nupkg
  force_update: true